// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_fuec4D20aL3Rt1sTxZTflIGzB0pOE4',
    appId: '1:453056602380:web:982d110ee85bc01202a929',
    messagingSenderId: '453056602380',
    projectId: 'dicoding-chatting-50e47',
    authDomain: 'dicoding-chatting-50e47.firebaseapp.com',
    storageBucket: 'dicoding-chatting-50e47.appspot.com',
    measurementId: 'G-BX80GMWF0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7wVCqHrr2dIl_tzkIYyKBPPQ66Rtx4C0',
    appId: '1:453056602380:android:51e4c3a5266a2ff702a929',
    messagingSenderId: '453056602380',
    projectId: 'dicoding-chatting-50e47',
    storageBucket: 'dicoding-chatting-50e47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYRKuUyAl2oyWR9Sbx1D8VRzN1iIZC5Q',
    appId: '1:453056602380:ios:ea353d35fa806a1902a929',
    messagingSenderId: '453056602380',
    projectId: 'dicoding-chatting-50e47',
    storageBucket: 'dicoding-chatting-50e47.appspot.com',
    iosClientId: '453056602380-tj2ch90aji122o2qaaa27dptci4hqt51.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
